POST http://localhost:8080/api/member
Content-Type: application/json

{
  "nickname": "",
  "kakaoId": "",
  "phone": "",
  "profileImg": "hi_profile_img.png"
}

###
GET http://localhost:8080/api/member?page=2

###
POST http://localhost:8080/api/walker
Content-Type: application/json

{
  "eventAgree": "AGREE",
  "name": "홍길동",
  "phone": "010-1234-6666",
  "birth": "",
  "address": "서울시 강남구",
  "email": "email@naver.com",
  "intro": "ㅎㅇㅎㅇ",
  "location1": "서울시 강남구"
}

###
GET http://localhost:8080/api/walker

###
POST http://localhost:8080/api/manager
Content-Type: application/json

{
  "nickname": "manager",
  "password": "1234"
}